version: '3'
services: 
    db:
        image: mysql:latest
        restart: always
        ports: 
            - '3306:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks: 
            - blog
    wordpress:
        depends_on:
            - db 
        image: wordpress:latest 
        ports: 
            - '8080:80'
        restart: always
        volumes: ['./wordpress_data:/var/www/html']
        environment: 
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWRD: wordpress
        networks: 
            - blog
networks: 
    blog:
        external: true
